### PR TITLE
Add sesseltjonna-csv to CSV benchmark suite

### PR DESCRIPTION
**Pull request by skjolber**

### CODE REVIEW

**Comment by arnaudroger** [comment]
Cheers will have a look, I run the benchmark with 20forks as there are a lot of variability in the Utd 8 encoding between runs so takes about 10hours just for the full file

**Comment by skjolber** [comment]
@arnaudroger great! Seems the initial merge went wrong, but the PR should be good now.

**Comment by arnaudroger** [comment]
try to ran the benchmark but it seem to got stuck with the parallelReader no idea why, running it again without it

**Comment by skjolber** [comment]
@arnaudroger thanks, will look into it, sounds strange.

**Comment by arnaudroger** [comment]
Just a guess by a read can return 0 maybe that’s not handled properly

**Comment by skjolber** [comment]
I agree, there is something there. Now 0 read means it is stuck in a loop.

**Comment by arnaudroger** [comment]
also was looking at the code to understand the perf difference. from what I see the parser assume the number of column will be constant across the file?
what happen with a csv 
```
a,b,c
a,b,c
a,b
a,b,c
```

also the end of line logic seem to support \r\n in some places what about mac convention with \r only?

**Comment by arnaudroger** [comment]
concerning the 0, it will return that if there is nothing availble to read in the buffer.
the alternative would be to block in the read method until there is something to read.
I'm not sure which one is better ....

**Comment by skjolber** [comment]
The parser does not support variable number of columns. Also I guess I got lazy so there is no support for mac line endings (we're running linux at work ;-)) 

First I thought there was something about the ASM databinding which made it fast, but now I think its is the simple parse loop;

```
do {
     ++currentOffset;
} while (current[currentOffset] != ',');
```

which makes the difference.

I guess reading 0 and yielding could be a configuration option.

**Comment by skjolber** [comment]
No able to recreate problems with the parallel reader (yet). Do you have some more details on the nature of the problem? It is filling a full 64kb of buffer per read, guess that might not be the case with the other readers.

**Comment by skjolber** [comment]
The parallell reader is really improving performance in your benchmarks, seems like an interesting performance addition. One of my use-cases is bootstrapping a service with a lot of data, I'll give it a go there.

**Comment by arnaudroger** [comment]
the parallel reader is actually blocking so I don't know will check if it happens again I'll get a threaddump

**Pull request merged**
